### ISSUE TITLE
(Just having some fun!) I don't like your tone, friend

### ISSUE THREAD

**Issue by cur33** [nstickney/exercism#1]
The readme says I can safely ignore this repo, but neither do I wish do ignore it nor do I wish to be safe about my ignorance, should I change my mind and select ignorance. I would suggest that you re-word this to be more inclusive of the nosier among us.
</joke>

You can safely ignore this issue.

**Comment by cur33** [comment]
That label needs to be way more common

**Comment by nstickney** [comment]
#truth

**Comment by cur33** [comment]
Actually did manage to find another use of the wontfix label 😆 and I have to say I agree with him. Don’t see any real gain to differentiating between js and jsx files.

https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904

**Comment by nstickney** [comment]
Yeah, I've seen `wontfix` in quite a few repositories, generally for stuff that is outside the scope of a project.

I do believe it is actually one of GitHub's preloaded tags for an issue.

**Comment by cur33** [comment]
Ah, that would make sense. I think the reason I like it so much is the phrasing. I understand its meaning and why it's the best solution to the out-of-scope problem, but I love how, rather than do something like just close it or mark it "not-a-problem", they use a phrase like "wontfix" that seems to imply that it *is* a problem, but they aren't gonna do nothin' about it. It comes across as sassy haha.

**Comment by nstickney** [comment]
Oh, I intend to sass, Mr. Rapp.
